[
  {
    "id": "-400200",
    "title": "AVA Family",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://familyhls.avatv.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/QwBGLzK.png"
  },
  {
    "id": "-400198",
    "title": "AVA Series",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://avaserieshls.wns.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/8AfAfZE.png"
  },
  {
    "id": "-400103",
    "title": "Bravo Farsi TV",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://bravoohls.wns.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.ibb.co/yynxRTS/Bravo-Farsi.jpg"
  },
  {
    "id": "-400102",
    "title": "Persian Film",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://pfilmhls.wns.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/AB0BaaA.png"
  },
  {
    "id": "-400101",
    "title": "persiana Sport",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "http://95.81.95.148:8080/hls2/persianas.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://alphasoftdev.com/apptv4/upload/persianaspo.jpg"
  },
  {
    "id": "-400100",
    "title": "Persiana One",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://onehls.persiana.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/X1Dv6st.png"
  },
  {
    "id": "-400099",
    "title": "Persiana Two",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://twohls.persiana.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://alphasoftdev.com/apptv4/upload/persiana2_200.png"
  },
  {
    "id": "-400098",
    "title": "Persiana Comedy",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://comedyhls.persiana.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/DBZ3Pi5.png"
  },
  {
    "id": "-400097",
    "title": "Persiana Family",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://familyhls.persiana.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/lMZsuWi.png"
  },
  {
    "id": "-400096",
    "title": "Persiana Korea",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://korhls.persiana.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/si2ZnIA.png"
  },
  {
    "id": "-400095",
    "title": "Persiana Music",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://musichls.persiana.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/SHxxi5I.png"
  },
  {
    "id": "-400093",
    "title": "Persiana Junior",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://junhls.persiana.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/zeKHZYG.png"
  },
  {
    "id": "-400092",
    "title": "Persiana RAP",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://raphls.persiana.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.ibb.co/ThGc7d5/Persiana-Rap.png"
  },
  {
    "id": "-400091",
    "title": "Persiana Cinema",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "ttps://cinehls.persiana.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/hgIro9r.png"
  },
  {
    "id": "-400090",
    "title": "Persiana Iranian",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://irhls.persiana.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/vqrrpBi.png"
  },
  {
    "id": "-400088",
    "title": "Persiana Plus",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://persiana-plus.icdndhcp.com/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/0xttibX.png"
  },
  {
    "id": "-400087",
    "title": "Persiana Nostalgia",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://noshls.persiana.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/SWO9CKA.png"
  },
  {
    "id": "-400086",
    "title": "Persiana Latino",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://latinohls.persiana.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://alphasoftdev.com/apptv4/upload/persiana2_200.png"
  },
  {
    "id": "-400085",
    "title": "Persiana HD",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://euhls.persiana.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.ibb.co/ZYDqMms/Persiana-HD.png"
  },
  {
    "id": "-400084",
    "title": "Persiana Turkiye",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://turkhls.persiana.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://alphasoftdev.com/apptv4/upload/persiana_turkiye200.png"
  },
  {
    "id": "-400083",
    "title": "Persiana Sonati",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://sonhls.persiana.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/yqq5PlP.png"
  },
  {
    "id": "-400082",
    "title": "javanantv",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://ir14.footballii.ir/hls2/javanantv.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://alphasoftdev.com/apptv4/upload/javanan.jpg"
  },
  {
    "id": "-400081",
    "title": "AMG",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://nl.livekadeh.com/hls2/AMG.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://alphasoftdev.com/apptv4/upload/amg.jpg"
  },
  {
    "id": "-400080",
    "title": "4Kurd",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://4kuhls.persiana.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://alphasoftdev.com/apptv4/upload/4_kurd200.png"
  },
  {
    "id": "-400069",
    "title": "طلوع افغانستان",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://af1.footballii.ir/dvrfl05/gin-tolohd/tracks-v1a1/mono.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://ayas.ir/icon/toloaf.png"
  },
  {
    "id": "-400068",
    "title": "ariana افغانستان",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://af2.footballii.ir/ariana/playlist.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://ayas.ir/icon/atn.png"
  },
  {
    "id": "-400067",
    "title": "Lemar افغانستان",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://af4.footballii.ir/master.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://ayas.ir/icon/lemar.png"
  },
  {
    "id": "-400066",
    "title": "1TV افغانستان",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://af1.footballii.ir/dvrfl05/gin-1tvafg/index-1697112525-now.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://ayas.ir/icon/1tv.png"
  },
  {
    "id": "-400065",
    "title": "Arezo افغانستان",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://af1.footballii.ir/dvrfl05/gin-arezotv/tracks-v1a1/mono.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://ayas.ir/icon/arezo.jpg"
  },
  {
    "id": "-400064",
    "title": "Tolo News افغانستان",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://af1.footballii.ir/dvrfl05/gin-tolonews/tracks-v1a1/mono.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://ayas.ir/icon/tolonews.png"
  },
  {
    "id": "-400061",
    "title": "4U TV",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://hls.4utv.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://alphasoftdev.com/apptv4/upload/7455-2019-02-09.jpg"
  },
  {
    "id": "-400060",
    "title": "Me2",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://me2hls.wns.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://alphasoftdev.com/apptv4/upload/me2_200.png"
  },
  {
    "id": "-400057",
    "title": "GEMBollywood",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://rs14.footballii.ir/memfs/52a1c937-986f-4a5d-8fa3-50cf9eec9df7.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://alphasoftdev.com/apptv4/upload/4370-2019-06-25.jpg"
  },
  {
    "id": "-400056",
    "title": "GEM Series",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://rs14.footballii.ir/memfs/79a9a557-a20e-4c0d-87b6-9147e079c989.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://alphasoftdev.com/apptv4/upload/7754-2019-02-03.png"
  },
  {
    "id": "-400055",
    "title": "Payame AfghanTV",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://g5nl6xx5lpq6-hls-live.5centscdn.com/live1234/2621b29e501b445fabf227b086123b70.sdp/mono.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://ayas.ir/icon/payameafghan.png"
  },
  {
    "id": "-400054",
    "title": "Afghan Nobel",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://live.relentlessinnovations.net:1936/afghannobel/afghannobel/playlist.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://ayas.ir/icon/afghannobel.png"
  },
  {
    "id": "-400044",
    "title": "Persiana Science",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://scihls.persiana.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://ayas.ir/icon/persianaScience.png"
  },
  {
    "id": "-400043",
    "title": "PersianFilm",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://pfilmhls.wns.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://alphasoftdev.com/apptv4/upload/persian_film200.png"
  },
  {
    "id": "-400042",
    "title": "Meta Film",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://metafilmhls.wns.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://alphasoftdev.com/apptv4/upload/metafilm200.png"
  },
  {
    "id": "-400040",
    "title": "ManoTo",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://edge-fr6.manoto.click/live.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://alphasoftdev.com/apptv4/upload/6296-2019-01-24.png"
  },
  {
    "id": "-400039",
    "title": "PMC",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://hls.pmchd.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/AbrHI7K.png"
  },
  {
    "id": "-400038",
    "title": "Oxir Channels",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://hls.oxir.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://alphasoftdev.com/apptv4/upload/oxir.png"
  },
  {
    "id": "-400037",
    "title": "247BoxTV",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://hls.247box.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://alphasoftdev.com/apptv4/upload/24BoxTV.jpg"
  },
  {
    "id": "-400036",
    "title": "ITN Channels",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://itnhls.wns.live/hls/stream.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://alphasoftdev.com/apptv4/upload/logo-itn.png"
  },
  {
    "id": "30000",
    "title": "Kurdistan 24",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://d1x82nydcxndze.cloudfront.net/live/index.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/9QWs2ms.png"
  },
  {
    "id": "30005",
    "title": "Kurd Channel",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://kurd-channel.ikoflix.com/hls/stream_2.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/xPwzad9.png"
  },
  {
    "id": "30010",
    "title": "Kurdistan TV",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://5a3ed7a72ed4b.streamlock.net/live/SMIL:myStream.smil/playlist.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/mjQptpc.png"
  },
  {
    "id": "30015",
    "title": "Kurdsat",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://ikomg2.mmdlive.lldns.net/ikomg2/366ca61db4c646a2bf9cd9f92dd6321c/manifest.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/UAbSwYA.png"
  },
  {
    "id": "30020",
    "title": "Kurdsat News",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://ikomg2.mmdlive.lldns.net/ikomg2/107b7df8f5444d778f349100739a09cd/manifest.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/F3XRwkt.png"
  },
  {
    "id": "30025",
    "title": "MBC Persia",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://shls-mbcpersia-prod-dub.shahid.net/out/v1/bdc7cd0d990e4c54808632a52c396946/index.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/YhLfb2V.png"
  },
  {
    "id": "400190",
    "title": "PBC Tapesh TV",
    "filter": "sat",
    "imgurl": "ayas",
    "channelurl": "https://iptv.tapesh.tv/tapesh/playlist.m3u8",
    "description": "",
    "type": "m3u8",
    "isOnline": "1",
    "urlImage": "https://i.imgur.com/5voEagF.png"
  }
]
